// Generates the neicon (vanilla) sources from data/icon-data.json.
// Emits src/{data,metadata}.ts. src/index.ts is hand-written and left untouched.
// Run: node scripts/generate.mjs   (or: bun run gen)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(PKG, '..', '..', 'data', 'icon-data.json');
const SRC = join(PKG, 'src');
const HEADER = '// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.\n';

const pascal = (name) =>
  name.split('-').map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');

const data = JSON.parse(readFileSync(DATA, 'utf8'));
const categories = Object.keys(data.categories);

const variantKeys = new Set();
const metas = [];
const iconData = {};
for (const category of categories) {
  for (const [name, def] of Object.entries(data.categories[category].icons)) {
    const variants = Object.keys(def.weights);
    variants.forEach((v) => variantKeys.add(v));
    iconData[name] = {};
    for (const v of variants) iconData[name][v] = def.weights[v].code;
    metas.push({
      name,
      component: pascal(name),
      category,
      description: def.description ?? [],
      variants,
    });
  }
}
const variantUnion = [...variantKeys].map((v) => JSON.stringify(v)).join(' | ');

const metadataSrc =
  HEADER +
  `export type Variant = ${variantUnion}\n\n` +
  `export const categories = ${JSON.stringify(categories)} as const\n` +
  `export type Category = (typeof categories)[number]\n\n` +
  `export interface IconMeta {\n` +
  `  /** kebab-case id, e.g. "down-arrow" */\n  name: string\n` +
  `  /** PascalCase component name, e.g. "DownArrow" */\n  component: string\n` +
  `  category: Category\n` +
  `  /** search keywords */\n  description: string[]\n` +
  `  /** available variant keys */\n  variants: Variant[]\n` +
  `}\n\n` +
  `export const icons: IconMeta[] = ${JSON.stringify(metas, null, 2)}\n`;

mkdirSync(SRC, { recursive: true });
writeFileSync(join(SRC, 'metadata.ts'), metadataSrc, 'utf8');
writeFileSync(
  join(SRC, 'data.ts'),
  HEADER +
    `import type { Variant } from './metadata.js'\n\n` +
    `/** Raw SVG markup keyed by icon name, then variant. */\n` +
    `export const iconData: Record<string, Record<Variant, string>> = ${JSON.stringify(iconData, null, 2)}\n`,
  'utf8',
);

console.log(`neicon: generated data + metadata for ${metas.length} icons (${[...variantKeys].join(', ')})`);
