// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
export type Variant = "B&W" | "Colored"

export const categories = ["general","files","communication","commerce","media","charts","arrows","letters","numbers"] as const
export type Category = (typeof categories)[number]

export interface IconMeta {
  /** kebab-case id, e.g. "down-arrow" */
  name: string
  /** PascalCase component name, e.g. "DownArrow" */
  component: string
  category: Category
  /** search keywords */
  description: string[]
  /** available variant keys */
  variants: Variant[]
}

export const icons: IconMeta[] = [
  {
    "name": "add",
    "component": "Add",
    "category": "general",
    "description": [
      "plus",
      "new",
      "create",
      "increase"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "apps",
    "component": "Apps",
    "category": "general",
    "description": [
      "grid",
      "applications",
      "dashboard",
      "widgets"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "attention",
    "component": "Attention",
    "category": "general",
    "description": [
      "warning",
      "alert",
      "exclamation",
      "caution",
      "error"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "bookmark",
    "component": "Bookmark",
    "category": "general",
    "description": [
      "save",
      "favorite",
      "ribbon",
      "tag"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "check",
    "component": "Check",
    "category": "general",
    "description": [
      "tick",
      "done",
      "confirm",
      "success",
      "checkmark",
      "ok"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "close",
    "component": "Close",
    "category": "general",
    "description": [
      "x",
      "cross",
      "cancel",
      "dismiss"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "delete",
    "component": "Delete",
    "category": "general",
    "description": [
      "trash",
      "bin",
      "garbage",
      "can"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "exit",
    "component": "Exit",
    "category": "general",
    "description": [
      "logout",
      "sign out",
      "door",
      "leave",
      "escape"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "filters",
    "component": "Filters",
    "category": "general",
    "description": [
      "filter",
      "sort",
      "funnel",
      "options",
      "refine"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "info",
    "component": "Info",
    "category": "general",
    "description": [
      "information",
      "help",
      "about",
      "details"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "layout",
    "component": "Layout",
    "category": "general",
    "description": [
      "grid",
      "wireframe",
      "dashboard",
      "columns",
      "template"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "menu",
    "component": "Menu",
    "category": "general",
    "description": [
      "hamburger",
      "list",
      "navigation",
      "bars"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "remove",
    "component": "Remove",
    "category": "general",
    "description": [
      "minus",
      "subtract",
      "decrease"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "hashtag",
    "component": "Hashtag",
    "category": "general",
    "description": [
      "hash",
      "pound",
      "number sign",
      "tag",
      "channel"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "time",
    "component": "Time",
    "category": "general",
    "description": [
      "clock",
      "schedule",
      "history",
      "watch",
      "hour"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "folder",
    "component": "Folder",
    "category": "files",
    "description": [
      "directory",
      "files",
      "archive",
      "documents"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "download",
    "component": "Download",
    "category": "files",
    "description": [
      "save",
      "import",
      "arrow down",
      "get"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "upload",
    "component": "Upload",
    "category": "files",
    "description": [
      "send",
      "export",
      "arrow up",
      "cloud"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "mail",
    "component": "Mail",
    "category": "communication",
    "description": [
      "email",
      "envelope",
      "message",
      "inbox",
      "letter"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "message",
    "component": "Message",
    "category": "communication",
    "description": [
      "chat",
      "comment",
      "bubble",
      "talk",
      "sms"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "basket",
    "component": "Basket",
    "category": "commerce",
    "description": [
      "cart",
      "shopping",
      "buy",
      "ecommerce",
      "store"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "credit-card",
    "component": "CreditCard",
    "category": "commerce",
    "description": [
      "payment",
      "card",
      "debit",
      "money",
      "checkout",
      "pay"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "play",
    "component": "Play",
    "category": "media",
    "description": [
      "start",
      "media",
      "control",
      "triangle"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "pause",
    "component": "Pause",
    "category": "media",
    "description": [
      "stop",
      "break",
      "media",
      "control"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "photo",
    "component": "Photo",
    "category": "media",
    "description": [
      "image",
      "picture",
      "camera",
      "gallery"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "video",
    "component": "Video",
    "category": "media",
    "description": [
      "film",
      "movie",
      "camera",
      "media"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "analytics",
    "component": "Analytics",
    "category": "charts",
    "description": [
      "bar chart",
      "statistics",
      "graph",
      "data",
      "report"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "pie-chart",
    "component": "PieChart",
    "category": "charts",
    "description": [
      "chart",
      "statistics",
      "graph",
      "data",
      "circle"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "up-arrow",
    "component": "UpArrow",
    "category": "arrows",
    "description": [
      "up",
      "arrow",
      "ascend",
      "north",
      "top"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "down-arrow",
    "component": "DownArrow",
    "category": "arrows",
    "description": [
      "down",
      "arrow",
      "descend",
      "south"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "left-arrow",
    "component": "LeftArrow",
    "category": "arrows",
    "description": [
      "left",
      "arrow",
      "back",
      "previous",
      "west"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "right",
    "component": "Right",
    "category": "arrows",
    "description": [
      "right",
      "arrow",
      "forward",
      "next",
      "east"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-a",
    "component": "LetterA",
    "category": "letters",
    "description": [
      "a",
      "A",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-b",
    "component": "LetterB",
    "category": "letters",
    "description": [
      "b",
      "B",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-c",
    "component": "LetterC",
    "category": "letters",
    "description": [
      "c",
      "C",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-d",
    "component": "LetterD",
    "category": "letters",
    "description": [
      "d",
      "D",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-e",
    "component": "LetterE",
    "category": "letters",
    "description": [
      "e",
      "E",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-f",
    "component": "LetterF",
    "category": "letters",
    "description": [
      "f",
      "F",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-g",
    "component": "LetterG",
    "category": "letters",
    "description": [
      "g",
      "G",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-h",
    "component": "LetterH",
    "category": "letters",
    "description": [
      "h",
      "H",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-j",
    "component": "LetterJ",
    "category": "letters",
    "description": [
      "j",
      "J",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-k",
    "component": "LetterK",
    "category": "letters",
    "description": [
      "k",
      "K",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-l",
    "component": "LetterL",
    "category": "letters",
    "description": [
      "l",
      "L",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-m",
    "component": "LetterM",
    "category": "letters",
    "description": [
      "m",
      "M",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-n",
    "component": "LetterN",
    "category": "letters",
    "description": [
      "n",
      "N",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-o",
    "component": "LetterO",
    "category": "letters",
    "description": [
      "o",
      "O",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-p",
    "component": "LetterP",
    "category": "letters",
    "description": [
      "p",
      "P",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-q",
    "component": "LetterQ",
    "category": "letters",
    "description": [
      "q",
      "Q",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-r",
    "component": "LetterR",
    "category": "letters",
    "description": [
      "r",
      "R",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-s",
    "component": "LetterS",
    "category": "letters",
    "description": [
      "s",
      "S",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-t",
    "component": "LetterT",
    "category": "letters",
    "description": [
      "t",
      "T",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-u",
    "component": "LetterU",
    "category": "letters",
    "description": [
      "u",
      "U",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-v",
    "component": "LetterV",
    "category": "letters",
    "description": [
      "v",
      "V",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-w",
    "component": "LetterW",
    "category": "letters",
    "description": [
      "w",
      "W",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-x",
    "component": "LetterX",
    "category": "letters",
    "description": [
      "x",
      "X",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-y",
    "component": "LetterY",
    "category": "letters",
    "description": [
      "y",
      "Y",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-z",
    "component": "LetterZ",
    "category": "letters",
    "description": [
      "z",
      "Z",
      "letter",
      "alphabet",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "letter-coin",
    "component": "LetterCoin",
    "category": "letters",
    "description": [
      "coin",
      "letter",
      "character"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "number-0",
    "component": "Number0",
    "category": "numbers",
    "description": [
      "0",
      "zero",
      "number",
      "digit",
      "numeric"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "number-1",
    "component": "Number1",
    "category": "numbers",
    "description": [
      "1",
      "one",
      "number",
      "digit",
      "numeric"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "number-2",
    "component": "Number2",
    "category": "numbers",
    "description": [
      "2",
      "two",
      "number",
      "digit",
      "numeric"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "number-3",
    "component": "Number3",
    "category": "numbers",
    "description": [
      "3",
      "three",
      "number",
      "digit",
      "numeric"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "number-4",
    "component": "Number4",
    "category": "numbers",
    "description": [
      "4",
      "four",
      "number",
      "digit",
      "numeric"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "number-5",
    "component": "Number5",
    "category": "numbers",
    "description": [
      "5",
      "five",
      "number",
      "digit",
      "numeric"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "number-6",
    "component": "Number6",
    "category": "numbers",
    "description": [
      "6",
      "six",
      "number",
      "digit",
      "numeric"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "number-7",
    "component": "Number7",
    "category": "numbers",
    "description": [
      "7",
      "seven",
      "number",
      "digit",
      "numeric"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "number-8",
    "component": "Number8",
    "category": "numbers",
    "description": [
      "8",
      "eight",
      "number",
      "digit",
      "numeric"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  },
  {
    "name": "number-9",
    "component": "Number9",
    "category": "numbers",
    "description": [
      "9",
      "nine",
      "number",
      "digit",
      "numeric"
    ],
    "variants": [
      "B&W",
      "Colored"
    ]
  }
]
