// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
import { NeiconBase, type NeiconProps } from '../base.js'

export function Basket(props: NeiconProps) {
  return (
    <NeiconBase
      {...props}
      variants={{
        colored: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="#39DBFF"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path d="M54 62L62 42H26L34 62H54Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M20.0919 38H67.9081L56.7081 66H31.2919L20.0919 38ZM31.9081 46L36.7081 58H51.2919L56.0919 46H31.9081Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M30 48H58V44H30V48Z" fill="#39DBFF"/><path fillRule="evenodd" clipRule="evenodd" d="M34 56H54V52H34V56Z" fill="#39DBFF"/><path fillRule="evenodd" clipRule="evenodd" d="M56.4223 43.7889L48.4223 27.7889L55.5777 24.2112L63.5777 40.2112L56.4223 43.7889Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M31.5777 43.7889L39.5777 27.7889L32.4223 24.2112L24.4223 40.2112L31.5777 43.7889Z" fill="black"/></>
        ),
        bw: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path d="M54 62L62 42H26L34 62H54Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M20.0918 38H67.9081L56.7081 66H31.2918L20.0918 38ZM31.9081 46L36.7081 58H51.2918L56.0918 46H31.9081Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M30 48H58V44H30V48Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M34 56H54V52H34V56Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M56.4224 43.7889L48.4224 27.7889L55.5778 24.2112L63.5778 40.2112L56.4224 43.7889Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M31.5776 43.7889L39.5776 27.7889L32.4222 24.2112L24.4222 40.2112L31.5776 43.7889Z" fill="black"/></>
        ),
      }}
    />
  )
}
