// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
import { NeiconBase, type NeiconProps } from '../base.js'

export function Exit(props: NeiconProps) {
  return (
    <NeiconBase
      {...props}
      variants={{
        colored: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="#FFB443"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path d="M62 64V24H26V64H62Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M22 20H66V68H22V20ZM30 28V60H58V28H30Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M47.7317 43.9999L37.963 32.6031L44.037 27.3967L58.2683 43.9999L44.037 60.6031L37.963 55.3967L47.7317 43.9999Z" fill="#FFB443"/><path fillRule="evenodd" clipRule="evenodd" d="M26 48H52V40H26V48Z" fill="#FFB443"/></>
        ),
        bw: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path d="M62 64V24H26V64H62Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M22 20H66V68H22V20ZM30 28V60H58V28H30Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M47.7319 43.9999L37.9632 32.6031L44.0373 27.3967L58.2686 43.9999L44.0373 60.6031L37.9632 55.3967L47.7319 43.9999Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M26 48H52V40H26V48Z" fill="white"/></>
        ),
      }}
    />
  )
}
