// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
import { NeiconBase, type NeiconProps } from '../base.js'

export function Layout(props: NeiconProps) {
  return (
    <NeiconBase
      {...props}
      variants={{
        colored: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="#39DBFF"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path d="M55 23H65V33H55V23Z" fill="black"/><path d="M55 39H65V49H55V39Z" fill="black"/><path d="M55 55H65V65H55V55Z" fill="black"/><path d="M39 23H49V33H39V23Z" fill="black"/><path d="M39 39H49V49H39V39Z" fill="black"/><path d="M39 55H49V65H39V55Z" fill="black"/><path d="M23 23H33V33H23V23Z" fill="black"/><path d="M23 39H33V49H23V39Z" fill="black"/><path d="M23 55H33V65H23V55Z" fill="black"/></>
        ),
        bw: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path d="M55 23H65V33H55V23Z" fill="black"/><path d="M55 39H65V49H55V39Z" fill="black"/><path d="M55 55H65V65H55V55Z" fill="black"/><path d="M39 23H49V33H39V23Z" fill="black"/><path d="M39 39H49V49H39V39Z" fill="black"/><path d="M39 55H49V65H39V55Z" fill="black"/><path d="M23 23H33V33H23V23Z" fill="black"/><path d="M23 39H33V49H23V39Z" fill="black"/><path d="M23 55H33V65H23V55Z" fill="black"/></>
        ),
      }}
    />
  )
}
