// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
import { NeiconBase, type NeiconProps } from '../base.js'

export function LetterM(props: NeiconProps) {
  return (
    <NeiconBase
      {...props}
      variants={{
        colored: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="#FF5E5E"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M40.3234 48.4243L52.3234 20.4243L59.6766 23.5757L47.6766 51.5757L40.3234 48.4243Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M56.0164 66.362L52.0164 22.362L59.9836 21.6377L63.9836 65.6377L56.0164 66.362Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M47.6766 48.4243L35.6766 20.4243L28.3234 23.5757L40.3234 51.5757L47.6766 48.4243Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M31.9836 66.362L35.9836 22.362L28.0164 21.6377L24.0164 65.6377L31.9836 66.362Z" fill="black"/></>
        ),
        bw: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M40.3236 48.4243L52.3236 20.4243L59.6768 23.5757L47.6768 51.5757L40.3236 48.4243Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M56.0167 66.362L52.0167 22.362L59.9839 21.6377L63.9839 65.6377L56.0167 66.362Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M47.6769 48.4243L35.6769 20.4243L28.3237 23.5757L40.3237 51.5757L47.6769 48.4243Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M31.9837 66.362L35.9837 22.362L28.0166 21.6377L24.0166 65.6377L31.9837 66.362Z" fill="black"/></>
        ),
      }}
    />
  )
}
