// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
import { NeiconBase, type NeiconProps } from '../base.js'

export function LetterW(props: NeiconProps) {
  return (
    <NeiconBase
      {...props}
      variants={{
        colored: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="#DD7DFF"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M40.1539 39.0991L48.1539 67.0991L55.8461 64.9014L47.8461 36.9014L40.1539 39.0991Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M60.1409 20.9478L48.1409 64.9478L55.859 67.0527L67.859 23.0527L60.1409 20.9478Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M47.8461 39.0991L39.8461 67.0991L32.1539 64.9014L40.1539 36.9014L47.8461 39.0991Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M27.859 20.9478L39.859 64.9478L32.1409 67.0527L20.1409 23.0527L27.859 20.9478Z" fill="black"/></>
        ),
        bw: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M40.154 39.0991L48.154 67.0991L55.8462 64.9014L47.8462 36.9014L40.154 39.0991Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M60.1413 20.9478L48.1413 64.9478L55.8594 67.0527L67.8594 23.0527L60.1413 20.9478Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M47.8465 39.0991L39.8465 67.0991L32.1543 64.9014L40.1543 36.9014L47.8465 39.0991Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M27.8592 20.9478L39.8592 64.9478L32.1411 67.0527L20.1411 23.0527L27.8592 20.9478Z" fill="black"/></>
        ),
      }}
    />
  )
}
