// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
import { NeiconBase, type NeiconProps } from '../base.js'

export function LetterX(props: NeiconProps) {
  return (
    <NeiconBase
      {...props}
      variants={{
        colored: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="#00FF75"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M54.6253 19.8525L26.6253 63.8525L33.3746 68.1475L61.3746 24.1475L54.6253 19.8525Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M33.3747 19.8525L61.3747 63.8525L54.6254 68.1475L26.6254 24.1475L33.3747 19.8525Z" fill="black"/></>
        ),
        bw: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M54.6257 19.8525L26.6257 63.8525L33.375 68.1475L61.375 24.1475L54.6257 19.8525Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M33.3748 19.8525L61.3748 63.8525L54.6255 68.1475L26.6255 24.1475L33.3748 19.8525Z" fill="black"/></>
        ),
      }}
    />
  )
}
