// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
import { NeiconBase, type NeiconProps } from '../base.js'

export function Mail(props: NeiconProps) {
  return (
    <NeiconBase
      {...props}
      variants={{
        colored: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="#FFF500"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path d="M64 60V28H24V60H64Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M20 24H68V64H20V24ZM28 32V56H60V32H28Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M23.932 35.691L26.068 32.3091L44 43.6346L61.932 32.3091L64.068 35.691L44 48.3656L23.932 35.691Z" fill="#FFF500"/></>
        ),
        bw: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path d="M64 60V28H24V60H64Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M20 24H68V64H20V24ZM28 32V56H60V32H28Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M23.9321 35.691L26.0681 32.3091L44.0001 43.6346L61.9321 32.3091L64.0681 35.691L44.0001 48.3656L23.9321 35.691Z" fill="white"/></>
        ),
      }}
    />
  )
}
