// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
import { NeiconBase, type NeiconProps } from '../base.js'

export function Number7(props: NeiconProps) {
  return (
    <NeiconBase
      {...props}
      variants={{
        colored: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="#FFF500"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M27.9999 20L59.9999 20L59.9999 28L27.9999 28L27.9999 20Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M63.7591 25.3672L47.7591 69.3672L40.2408 66.6332L56.2408 22.6332L63.7591 25.3672Z" fill="black"/></>
        ),
        bw: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M28 20L60 20L60 28L28 28L28 20Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M63.7591 25.3672L47.7591 69.3672L40.2407 66.6332L56.2407 22.6332L63.7591 25.3672Z" fill="black"/></>
        ),
      }}
    />
  )
}
