// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
import { NeiconBase, type NeiconProps } from '../base.js'

export function UpArrow(props: NeiconProps) {
  return (
    <NeiconBase
      {...props}
      variants={{
        colored: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="#00FF75"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M44 31.657L30.8284 44.8285L25.1716 39.1717L44 20.3433L62.8284 39.1717L57.1716 44.8285L44 31.657Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M48 68L48 26L40 26L40 68L48 68Z" fill="black"/></>
        ),
        bw: (
          <><path d="M18 18H86V86H18V18Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M16 18C16 16.8954 16.8954 16 18 16H86C87.1046 16 88 16.8954 88 18V86C88 87.1046 87.1046 88 86 88H18C16.8954 88 16 87.1046 16 86V18ZM20 20V84H84V20H20Z" fill="black"/><path d="M10 10H78V78H10V10Z" fill="white"/><path fillRule="evenodd" clipRule="evenodd" d="M8 10C8 8.89543 8.89543 8 10 8H78C79.1046 8 80 8.89543 80 10V78C80 79.1046 79.1046 80 78 80H10C8.89543 80 8 79.1046 8 78V10ZM12 12V76H76V12H12Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M43.9998 31.657L30.8282 44.8285L25.1714 39.1717L43.9998 20.3433L62.8282 39.1717L57.1714 44.8285L43.9998 31.657Z" fill="black"/><path fillRule="evenodd" clipRule="evenodd" d="M48 68L48 26L40 26L40 68L48 68Z" fill="black"/></>
        ),
      }}
    />
  )
}
