// Generates neicon-react components + metadata from data/icon-data.json.
// Emits src/icons/*.tsx, src/icons/index.ts, src/{index,all,metadata}.ts.
// src/base.tsx is hand-written and left untouched.
// Run: node scripts/generate.mjs   (or: bun run gen)
import { readFileSync, writeFileSync, rmSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(PKG, '..', '..', 'data', 'icon-data.json');
const SRC = join(PKG, 'src');
const ICONS = join(SRC, 'icons');
const HEADER = '// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.\n';

const pascal = (name) =>
  name.split('-').map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');

// Kebab SVG attributes -> JSX camelCase.
const SVG_ATTR = {
  'fill-rule': 'fillRule',
  'clip-rule': 'clipRule',
  'stroke-width': 'strokeWidth',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
  'stroke-miterlimit': 'strokeMiterlimit',
  'stroke-dasharray': 'strokeDasharray',
  'stroke-opacity': 'strokeOpacity',
  'fill-opacity': 'fillOpacity',
  'stop-color': 'stopColor',
  'stop-opacity': 'stopOpacity',
  'clip-path': 'clipPath',
};
const toInnerJsx = (svg) => {
  let inner = svg.replace(/^<svg\b[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  for (const [k, v] of Object.entries(SVG_ATTR)) inner = inner.replaceAll(`${k}=`, `${v}=`);
  return inner;
};

const data = JSON.parse(readFileSync(DATA, 'utf8'));
const categories = Object.keys(data.categories);

const variantKeys = new Set();
const metas = [];
const comps = [];
for (const category of categories) {
  for (const [name, def] of Object.entries(data.categories[category].icons)) {
    const variants = Object.keys(def.weights);
    variants.forEach((v) => variantKeys.add(v));
    metas.push({
      name,
      component: pascal(name),
      category,
      description: def.description ?? [],
      variants,
    });
    comps.push({
      name,
      component: pascal(name),
      colored: toInnerJsx(def.weights['Colored'].code),
      bw: toInnerJsx(def.weights['B&W'].code),
    });
  }
}
const variantUnion = [...variantKeys].map((v) => JSON.stringify(v)).join(' | ');

const metadataSrc =
  HEADER +
  `export type Variant = ${variantUnion}\n\n` +
  `export const categories = ${JSON.stringify(categories)} as const\n` +
  `export type Category = (typeof categories)[number]\n\n` +
  `export interface IconMeta {\n` +
  `  /** kebab-case id, e.g. "down-arrow" */\n  name: string\n` +
  `  /** PascalCase component name, e.g. "DownArrow" */\n  component: string\n` +
  `  category: Category\n` +
  `  /** search keywords */\n  description: string[]\n` +
  `  /** available variant keys */\n  variants: Variant[]\n` +
  `}\n\n` +
  `export const icons: IconMeta[] = ${JSON.stringify(metas, null, 2)}\n`;

// Reset the generated icons directory (base.tsx lives one level up, untouched).
rmSync(ICONS, { recursive: true, force: true });
mkdirSync(ICONS, { recursive: true });

for (const c of comps) {
  const file =
    HEADER +
    `import { NeiconBase, type NeiconProps } from '../base.js'\n\n` +
    `export function ${c.component}(props: NeiconProps) {\n` +
    `  return (\n` +
    `    <NeiconBase\n` +
    `      {...props}\n` +
    `      variants={{\n` +
    `        colored: (\n          <>${c.colored}</>\n        ),\n` +
    `        bw: (\n          <>${c.bw}</>\n        ),\n` +
    `      }}\n` +
    `    />\n` +
    `  )\n` +
    `}\n`;
  writeFileSync(join(ICONS, `${c.component}.tsx`), file, 'utf8');
}

writeFileSync(
  join(ICONS, 'index.ts'),
  HEADER + comps.map((c) => `export { ${c.component} } from './${c.component}.js'`).join('\n') + '\n',
  'utf8',
);

writeFileSync(join(SRC, 'metadata.ts'), metadataSrc, 'utf8');

writeFileSync(
  join(SRC, 'index.ts'),
  HEADER + `export * from './base.js'\nexport * from './icons/index.js'\nexport * from './metadata.js'\n`,
  'utf8',
);

writeFileSync(
  join(SRC, 'all.ts'),
  HEADER +
    `import type { ComponentType } from 'react'\n` +
    `import type { NeiconProps } from './base.js'\n` +
    `import * as Icons from './icons/index.js'\n\n` +
    `/** Every icon keyed by its kebab-case name. Importing this pulls the whole set. */\n` +
    `export const iconComponents: Record<string, ComponentType<NeiconProps>> = {\n` +
    comps.map((c) => `  ${JSON.stringify(c.name)}: Icons.${c.component},`).join('\n') +
    `\n}\n\n` +
    `export * from './base.js'\nexport * from './metadata.js'\n`,
  'utf8',
);

console.log(`neicon-react: generated ${comps.length} components + metadata (${[...variantKeys].join(', ')})`);
